//GET GUIDE PROFILE
export const FETCH_GUIDE_PROFILE_REQUESTED = 'FETCH_GUIDE_PROFILE_REQUESTED';
export const FETCH_GUIDE_PROFILE_SUCCESSED = 'FETCH_GUIDE_PROFILE_SUCCESSED';
export const FETCH_GUIDE_PROFILE_FAILED = 'FETCH_GUIDE_PROFILE_FAILED';

//GET GUIDE PROFILE DATA (POBIERA PROFIL UZYTKOWNIKA)
export const FETCH_GUIDE_PROFILE_DATA_REQUESTED = 'FETCH_GUIDE_PROFILE_DATA_REQUESTED';
export const FETCH_GUIDE_PROFILE_DATA_SUCCESSED = 'FETCH_GUIDE_PROFILE_DATA_SUCCESSED';
export const FETCH_GUIDE_PROFILE_DATA_FAILED = 'FETCH_GUIDE_PROFILE_DATA_FAILED';

//GET GUIDE ACTIVE OFFERS
export const FETCH_GUIDE_ACTIVE_OFFERS_REQUESTED = 'FETCH_ACTIVE_OFFERS_REQUESTED';
export const FETCH_GUIDE_ACTIVE_OFFERS_SUCCESSED = 'FETCH_ACTIVE_OFFERS_SUCCESSED';
export const FETCH_GUIDE_ACTIVE_OFFERS_FAILED = 'FETCH_ACTIVE_OFFERS_FAILED';

//GET GUIDE HISTORY OFFERS
export const FETCH_GUIDE_HISTORY_REQUESTED = 'FETCH_GUIDE_HISTORY_OFFERS_REQUESTED';
export const FETCH_GUIDE_HISTORY_SUCCESSED = 'FETCH_GUIDE_HISTORY_SUCCESSED';
export const FETCH_GUIDE_HISTORY_FAILED = 'FETCH_GUIDE_HISTORY_FAILED';
