export const GET_GUIDE_REQUESTS = 'GET_GUIDE_REQUESTS';
export const GET_GUIDE_REQUESTS_SUCCESSED = 'GET_GUIDE_REQUESTS_SUCCESSED';
export const GET_GUIDE_REQUESTS_FAILED = 'GET_GUIDE_REQUESTS_FAILED';

export const SETTLE_GUIDE_REQUEST = 'SETTLE_GUIDE_REQUEST';
export const SETTLE_GUIDE_REQUEST_SUCCESSED = 'SETTLE_GUIDE_REQUEST_SUCCESSED';
export const SETTLE_GUIDE_REQUEST_FAILED = 'SETTLE_GUIDE_REQUEST_FAILED';
