export const GET_GUIDE_REQUESTS = 'GET_GUIDE_REQUESTS';
export const GET_GUIDE_REQUESTS_SUCCESSED = 'GET_GUIDE_REQUESTS_SUCCESSED';
export const GET_GUIDE_REQUESTS_FAILED = 'GET_GUIDE_REQUESTS_FAILED';
