export const SIGN_UP_GOOGLE_REQUESTED = 'SIGN_UP_GOOGLE_REQUESTED';
export const SIGN_UP_GOOGLE_SUCCESSED = 'SIGN_UP_GOOGLE_SUCCESSED';
export const SIGN_UP_GOOGLE_FAILED = 'SIGN_UP_GOOGLE_FAILED';

export const CONFIRM_SIGN_UP_REQUESTED = 'CONFIRM_SIGN_UP_REQUESTED';
export const CONFIRM_SIGN_UP_SUCCESSED = 'CONFIRM_SIGN_UP_SUCCESSED';
export const CONFIRM_SIGN_UP_FAILED = 'CONFIRM_SIGN_UP_FAILED';

export const GET_INTERESTS_REQUESTED = 'GET_INTERESTS_REQUESTED';
export const GET_INTERESTS_SUCCESSED = 'GET_INTERESTS_SUCCESSED';
export const GET_INTERESTS_FAILED = 'GET_INTERESTS_FAILED';
