export const SIGN_UP_GOOGLE_USER_REQUESTED = 'SIGN_UP_GOOGLE_USER_REQUESTED';
export const SIGN_UP_GOOGLE_USER_SUCCESSED = 'SIGN_UP_GOOGLE_USER_SUCCESSED';
export const SIGN_UP_GOOGLE_USER_FAILED = 'SIGN_UP_GOOGLE_USER_FAILED';
