export const LOG_IN_GOOGLE_REQUESTED = 'LOG_IN_GOOGLE_REQUESTED';
export const LOG_IN_GOOGLE_SUCCESSED = 'LOG_IN_GOOGLE_SUCCESSED';
export const LOG_IN_GOOGLE_FAILED = 'LOG_IN_GOOGLE_FAILED';

export const LOG_OUT_GOOGLE_REQUESTED = 'LOG_OUT_GOOGLE_REQUESTED';
export const LOG_OUT_GOOGLE_SUCCESSED = 'LOG_OUT_GOOGLE_SUCCESSED';
export const LOG_OUT_GOOGLE_FAILED = 'LOG_OUT_GOOGLE_FAILED';

export const EDIT_PROFILE_REQUESTED = 'EDIT_PROFILE_REQUESTED';
export const EDIT_PROFILE_SUCCESSED = 'EDIT_PROFILE_SUCCESSED';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

