export const LOG_IN_GOOGLE_REQUESTED = 'LOG_IN_GOOGLE_REQUESTED';
export const LOG_IN_GOOGLE_SUCCESSED = 'LOG_IN_GOOGLE_SUCCESSED';
export const LOG_IN_GOOGLE_FAILED = 'LOG_IN_GOOGLE_FAILED';

export const LOG_OUT_GOOGLE_REQUESTED = 'LOG_OUT_GOOGLE_REQUESTED';
export const LOG_OUT_GOOGLE_SUCCESSED = 'LOG_OUT_GOOGLE_SUCCESSED';
export const LOG_OUT_GOOGLE_FAILED = 'LOG_OUT_GOOGLE_FAILED';

export const GET_PROFILE_REQUESTED = 'GET_PROFILE_REQUESTED';
export const GET_PROFILE_SUCCESSED = 'GET_PROFILE_SUCCESSED';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAIELD';

export const EDIT_PROFILE_REQUESTED = 'EDIT_PROFILE_REQUESTED';
export const EDIT_PROFILE_SUCCESSED = 'EDIT_PROFILE_SUCCESSED';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

export const SEND_AVATAR_REQUESTED = 'SEND_AVATAR_REQUESTED';
export const SEND_AVATAR_SUCCESSED = 'SEND_AVATAR_SUCCESSED';
export const SEND_AVATAR_FAILED = 'SEND_AVATAR_FAILED';
