export const ADD_TASK = 'ADD_TASK';
export const FETCH_TASKS_REQUESTED = 'FETCH_TASKS_REQUESTED';
export const FETCH_TASKS_SUCCESSED = 'FETCH_TASKS_SUCCESSED';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';
