export const ADD_USER = 'ADD_USER';
export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
export const FETCH_USERS_SUCCESSED = 'FETCH_USERS_SUCCESSED';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
