export const CLEAN_USER_PROFILES = 'CLEAN_USER_PROFILES';
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESED = 'FETCH_USER_PROFILE_SUCCESSED';
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
