// GET 10 RANDOM TRIPS FROM API
export const FETCH_RANDOM_TRIPS_REQUESTED = 'FETCH_RANDOM_TRIPS_REQUESTED';
export const FETCH_RANDOM_TRIPS_SUCCESED = 'FETCH_RANDOM_TRIPS_SUCCESED';
export const FETCH_RANDOM_TRIPS_FAILED = 'FETCH_RANDOM_TRIPS_FAILED';

//GET ALL OFFERS BY NAME
export const FETCH_NAME_TRIPS_REQUESTED = 'FETCH_NAME_TRIPS_REQUESTED';
export const FETCH_NAME_TRIPS_SUCCESED = 'FETCH_NAME_TRIPS_SUCCESED';
export const FETCH_NAME_TRIPS_FAILED = 'FETCH_NAME_TRIPS_FAILED';

//GET ALL OFFERS BY GEO
export const FETCH_GEO_TRIPS_REQUESTED = 'FETCH_GEO_TRIPS_REQUESTED';
export const FETCH_GEO_TRIPS_SUCCESED = 'FETCH_GEO_TRIPS_SUCCESED';
export const FETCH_GEO_TRIPS_FAILED = 'FETCH_GEO_TRIPS_FAILED';

//GET ALL TAGS FROM API
export const FETCH_TAGS_REQUESTED = 'FETCH_TAGS_REQUESTED';
export const FETCH_TAGS_SUCCESED = 'FETCH_TAGS_SUCCESED';
export const FETCH_TAGS_FAILED = 'FETCH_TAGS_FAILED';

//GET SUGGESTED CITIES FROM PHOTON API
export const FETCH_SUGGESTED_CITIES_REQUESTED = 'FETCH_SUGGESTED_CITIES_REQUESTED';
export const FETCH_SUGGESTED_CITIES_SUCCESED = 'FETCH_SUGGESTED_CITIES_SUCCESED';
export const FETCH_SUGGESTED_CITIES_FAILED = 'FETCH_SUGGESTED_CITIES_FAILED';
