export const FETCH_TRIPS_REQUESTED = "FETCH_TRIPS_REQUESTED";
export const FETCH_TRIPS_SUCCESED = "FETCH_TRIPS_SUCCESED";
export const FETCH_TRIPS_FAILED = "FETCH_TRIPS_FAILED";
export const FILTER_TRIPS = "FILTER_TRIPS";
export const SET_ACTIVE_TAGS = "SET_ACTIVE_TAGS";
