// GET 10 RANDOM TRIPS FROM API
export const FETCH_RANDOM_TRIPS_REQUESTED = 'FETCH_RANDOM_TRIPS_REQUESTED';
export const FETCH_RANDOM_TRIPS_SUCCESED = 'FETCH_RANDOM_TRIPS_SUCCESED';
export const FETCH_RANDOM_TRIPS_FAILED = 'FETCH_RANDOM_TRIPS_FAILED';

//GET ALL OFFERS BY CITY
export const FETCH_CITY_TRIPS_REQUESTED = 'FETCH_CITY_TRIPS_REQUESTED';
export const FETCH_CITY_TRIPS_SUCCESED = 'FETCH_CITY_TRIPS_SUCCESED';
export const FETCH_CITY_TRIPS_FAILED = 'FETCH_CITY_TRIPS_FAILED';

//GET ALL OFFERS BY GEO
export const FETCH_GEO_TRIPS_REQUESTED = 'FETCH_GEO_TRIPS_REQUESTED';
export const FETCH_GEO_TRIPS_SUCCESED = 'FETCH_GEO_TRIPS_SUCCESED';
export const FETCH_GEO_TRIPS_FAILED = 'FETCH_GEO_TRIPS_FAILED';

//GET ALL TAGS FROM API
export const FETCH_TAGS_REQUESTED = 'FETCH_TAGS_REQUESTED';
export const FETCH_TAGS_SUCCESED = 'FETCH_TAGS_SUCCESED';
export const FETCH_TAGS_FAILED = 'FETCH_TAGS_FAILED';

//GET SUGGESTED CITIES FROM PHOTON API
export const FETCH_SUGGESTED_CITIES_REQUESTED = 'FETCH_SUGGESTED_CITIES_REQUESTED';
export const FETCH_SUGGESTED_CITIES_SUCCESED = 'FETCH_SUGGESTED_CITIES_SUCCESED';
export const FETCH_SUGGESTED_CITIES_FAILED = 'FETCH_SUGGESTED_CITIES_FAILED';

//GET GUIDE PROFILE
export const FETCH_GUIDE_PROFILE_REQUESTED = 'FETCH_GUIDE_PROFILE_REQUESTED';
export const FETCH_GUIDE_PROFILE_SUCCESSED = 'FETCH_GUIDE_PROFILE_SUCCESSED';
export const FETCH_GUIDE_PROFILE_FAILED = 'FETCH_GUIDE_PROFILE_FAILED';

//GET GUIDE PROFILE DATA
export const FETCH_GUIDE_PROFILE_DATA_REQUESTED = 'FETCH_GUIDE_PROFILE_DATA_REQUESTED';
export const FETCH_GUIDE_PROFILE_DATA_SUCCESSED = 'FETCH_GUIDE_PROFILE_DATA_SUCCESSED';
export const FETCH_GUIDE_PROFILE_DATA_FAILED = 'FETCH_GUIDE_PROFILE_DATA_FAILED';

//GET GUIDE ACTIVE OFFERS
export const FETCH_GUIDE_ACTIVE_OFFERS_REQUESTED = 'FETCH_ACTIVE_OFFERS_REQUESTED';
export const FETCH_GUIDE_ACTIVE_OFFERS_SUCCESSED = 'FETCH_ACTIVE_OFFERS_SUCCESSED';
export const FETCH_GUIDE_ACTIVE_OFFERS_FAILED = 'FETCH_ACTIVE_OFFERS_FAILED';

//GET GUIDE HISTORY OFFERS
export const FETCH_GUIDE_HISTORY_REQUESTED = 'FETCH_GUIDE_HISTORY_OFFERS_REQUESTED';
export const FETCH_GUIDE_HISTORY_SUCCESSED = 'FETCH_GUIDE_HISTORY_SUCCESSED';
export const FETCH_GUIDE_HISTORY_FAILED = 'FETCH_GUIDE_HISTORY_FAILED';
