export const CREATE_OFFER_REQUESTED = 'CREATE_OFFER_REQUESTED';
export const CREATE_OFFER_SUCCESSED = 'CREATE_OFFER_SUCCESSED';
export const CREATE_OFFER_FAILED = 'CREATE_OFFER_FAILED';

export const GET_OFFER_BY_ID_REQUESTED = 'GET_OFFER_BY_ID_REQUESTED';
export const GET_OFFER_BY_ID_SUCCESSED = 'GET_OFFER_BY_ID_SUCCESSED';
export const GET_OFFER_BY_ID_FAILED = 'GET_OFFER_BY_ID_FAILED';
