export const CREATE_OFFER_REQUESTED = 'CREATE_OFFER_REQUESTED';
export const CREATE_OFFER_SUCCESSED = 'CREATE_OFFER_SUCCESSED';
export const CREATE_OFFER_FAILED = 'CREATE_OFFER_FAILED';

export const GET_OFFER_BY_ID_REQUESTED = 'GET_OFFER_BY_ID_REQUESTED';
export const GET_OFFER_BY_ID_SUCCESSED = 'GET_OFFER_BY_ID_SUCCESSED';
export const GET_OFFER_BY_ID_FAILED = 'GET_OFFER_BY_ID_FAILED';

export const BUY_OFFER_REQUESTED = 'BUY_OFFER_REQUESTED';
export const BUY_OFFER_SUCCESSED = 'BUY_OFFER_SUCCESSED';
export const BUY_OFFER_FAILED = 'BUY_OFFER_FAILED';

export const GET_ACTIVE_OFFERS_REQUESTED = 'GET_ACTIVE_OFFERS_REQUESTED';
export const GET_ACTIVE_OFFERS_SUCCESSED = 'GET_ACTIVE_OFFERS_SUCCESSED';
export const GET_ACTIVE_OFFERS_FAILED = 'GET_ACTIVE_OFFERS_FAILED';

export const GET_APPROACHES_REQUESTED = 'GET_APPROACHES_REQUESTED';
export const GET_APPROACHES_SUCCESSED = 'GET_APPROACHES_SUCCESSED';
export const GET_APPROACHES_FAILED = 'GET_APPROACHES_FAILED';

export const SETTLE_ACTIVE_OFFER_REQUESTED = 'SETTLE_ACTIVE_OFFER_REQUESTED';
export const SETTLE_ACTIVE_OFFER_SUCCESSED = 'SETTLE_ACTIVE_OFFER_SUCCESSED';
export const SETTLE_ACTIVE_OFFER_FAILED = 'SETTLE_ACTIVE_OFFER_FAILED';

export const CREATE_AGREEMENT_REQUESTED = 'CREATE_AGREEMENT_REQUESTED';
export const CREATE_AGREEMENT_SUCCESSED = 'CREATE_AGREEMENT_SUCCESSED';
export const CREATE_AGREEMENT_FAILED = 'CREATE_AGREEMENT_FAILED';

export const GET_OWN_AGREEMENTS_REQUESTED = 'GET_OWN_AGREEMENTS_REQUESTED';
export const GET_OWN_AGREEMENTS_SUCCESSED = 'GET_OWN_AGREEMENTS_SUCCESSED';
export const GET_OWN_AGREEMENTS_FAILED = 'GET_OWN_AGREEMENTS_FAILED';

export const SETTLE_AGREEMENT_REQUESTED = 'SETTLE_AGREEMENT_REQUESTED';
export const SETTLE_AGREEMENT_SUCCESSED = 'SETTLE_AGREEMENT_SUCCESSED';
export const SETTLE_AGREEMENT_FAILED = 'SETTLE_AGREEMENT_FAILED';

export const REPORT_OFFER_REQUESTED = 'REPORT_OFFER_REQUESTED';

export const ADD_FEEDBACK_REQUESTED = 'ADD_FEEDBACK_REQUESTED';
