export const CREATE_OFFER_REQUESTED = 'CREATE_OFFER_REQUESTED';
export const CREATE_OFFER_SUCCESSED = 'CREATE_OFFER_SUCCESSED';
export const CREATE_OFFER_FAILED = 'CREATE_OFFER_FAILED';

export const GET_OFFER_BY_ID_REQUESTED = 'GET_OFFER_BY_ID_REQUESTED';
export const GET_OFFER_BY_ID_SUCCESSED = 'GET_OFFER_BY_ID_SUCCESSED';
export const GET_OFFER_BY_ID_FAILED = 'GET_OFFER_BY_ID_FAILED';

export const BUY_OFFER_REQUESTED = 'BUY_OFFER_REQUESTED';
export const BUY_OFFER_SUCCESSED = 'BUY_OFFER_SUCCESSED';
export const BUY_OFFER_FAILED = 'BUY_OFFER_FAILED';

export const GET_ACTIVE_OFFERS_REQUESTED = 'GET_ACTIVE_OFFERS_REQUESTED';
export const GET_ACTIVE_OFFERS_SUCCESSED = 'GET_ACTIVE_OFFERS_SUCCESSED';
export const GET_ACTIVE_OFFERS_FAILED = 'GET_ACTIVE_OFFERS_FAILED';

export const GET_APPROACHES_REQUESTED = 'GET_APPROACHES_REQUESTED';
export const GET_APPROACHES_SUCCESSED = 'GET_APPROACHES_SUCCESSED';
export const GET_APPROACHES_FAILED = 'GET_APPROACHES_FAILED';
